// tenant-contract.test.ts — CTC-2004. The SDK's own declaration of GET /api/v1/agent/contract, pinned
// against the cloud's committed fixture.
//
// `@catalyst-cloud/types` (where the cloud declares `TenantContract`) is private and unpublished, so
// this SDK owns a copy — the same discipline `src/types.ts` states for the change-feed contract. The
// drift detector is the fixture the cloud commits at packages/types/fixtures/tenant-contract.fixture.json
// (built by the real `buildTenantContract` over a synthetic tenant, regenerated by `bun run
// contract:fixture`, and published to consumers for exactly this purpose — docs/agent-contract.md
// "Tier 2"). A copy lives under test/fixtures/; when the cloud's document changes shape, the copy is
// refreshed and this file reddens on the delta.
//
// ⚠️ THIS COPY IS ROUTE-PARTIAL, NOT VERSION-CURRENT (CTC-2562): it carries the routes[] rows this
// SDK actually wraps (plus the two `project-repositories` rows added at `since: "1.11.0"`), not every
// route the cloud's real 1.11.0 document lists — `account-environment` and others are still absent.
// Its `contractVersion` stays "1.0.0" on purpose: bumping it here would assert a completeness this
// fixture does not have. A full refresh needs the cloud's own regenerated fixture.
//
// ⛔ A JSON import is WIDENED by tsc (`"POST"` becomes `string`), so `fixture satisfies TenantContract`
// cannot be the check. The check is the runtime guard the client itself uses on every 200 —
// `readTenantContract` — plus a compile-time lockstep between the type's key set and the guard's
// REQUIRED key list, so a field added to the type without a guard clause is a compile error here.

import { describe, expect, it } from "vitest";
import fixture from "./fixtures/tenant-contract.fixture.json";
import {
  CONTRACT_ROUTE,
  TENANT_CONTRACT_KEYS,
  labelIdFor,
  readTenantContract,
  routeByName,
  stageIdForSlot,
  teamByKey,
  teamForTicket,
  type TenantContract,
} from "../src/tenant-contract";

/** Compile-time exact type equality (same device as entity-names-drift.test.ts). */
type TypesAreEqual<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;

/** A compile error HERE is the failure: the guard's key list and the type's key set disagree. */
const keysInLockstep: TypesAreEqual<(typeof TENANT_CONTRACT_KEYS)[number], keyof TenantContract> =
  true;

function loaded(): TenantContract {
  const doc = readTenantContract(fixture);
  if (doc === null) throw new Error("the committed fixture does not read as a TenantContract");
  return doc;
}

describe("CTC-2004 — the SDK's TenantContract tracks the cloud's committed fixture", () => {
  it("⭐ the fixture reads as a TenantContract through the same guard the client applies on the wire", () => {
    expect(keysInLockstep).toBe(true);
    expect(readTenantContract(fixture)).not.toBeNull();
  });

  it("⭐ the fixture's top-level key set is EXACTLY the type's key set (order-independent)", () => {
    expect(Object.keys(fixture).sort()).toEqual([...TENANT_CONTRACT_KEYS].sort());
  });

  it("⛔ NEGATIVE CONTROL — the guard refuses a document missing a required leg", () => {
    // Prove the instrument can fire: the same fixture with one top-level key deleted must not read.
    const { teams: _teams, ...withoutTeams } = fixture;
    expect(readTenantContract(withoutTeams)).toBeNull();
    expect(readTenantContract(null)).toBeNull();
    expect(readTenantContract("not a document")).toBeNull();
    expect(readTenantContract({ ...fixture, routes: "not-an-array" })).toBeNull();
    expect(readTenantContract({ ...fixture, cache: { maxAgeSeconds: "900" } })).toBeNull();
  });

  it("⛔ P2 (Codex #65 r1) — the guard refuses a team whose nested legs are malformed, before any accessor can throw", () => {
    const team = fixture.teams[0]!;
    const withTeam = (patch: Record<string, unknown>) => ({ ...fixture, teams: [{ ...team, ...patch }] });
    expect(readTenantContract(withTeam({ labels: {} }))).toBeNull();
    expect(readTenantContract(withTeam({ labels: { ask: [], hold: "nope", release: [] } }))).toBeNull();
    expect(readTenantContract(withTeam({ labels: { ...team.labels, ask: [{ name: 1 }] } }))).toBeNull();
    expect(readTenantContract(withTeam({ key: 5 }))).toBeNull();
    expect(readTenantContract(withTeam({ stages: { research: {} } }))).toBeNull();
    expect(readTenantContract(withTeam({ stages: { research: { ...team.stages.research, stateStillExists: "yes" } } }))).toBeNull();
    expect(readTenantContract(withTeam({ readiness: {} }))).toBeNull();
    expect(readTenantContract(withTeam({ readiness: { ...team.readiness, checks: "none" } }))).toBeNull();
    // Positive control for the instrument: the untouched team still reads, and so does one with a
    // null key and an empty (but well-formed) stage map — both legal on the wire.
    expect(readTenantContract(withTeam({}))).not.toBeNull();
    expect(readTenantContract(withTeam({ key: null, stages: {} }))).not.toBeNull();
  });

  it("the one path a consumer knows a priori is the contract route itself", () => {
    expect(CONTRACT_ROUTE).toBe("/api/v1/agent/contract");
    expect(loaded().routes.some((r) => r.path === CONTRACT_ROUTE)).toBe(true);
  });
});

describe("CTC-2004 — the pure accessors the bundle's contract.ts carries today, returning results", () => {
  it("routeByName resolves by the LAST path segment, never a literal path", () => {
    const doc = loaded();
    expect(routeByName(doc, "issue-comment")).toEqual({
      method: "POST",
      path: "/api/v1/agent/issue-comment",
      takesWriteBudgetUnit: true,
      since: "1.0.0",
    });
    expect(routeByName(doc, "attachments")?.method).toBe("GET");
    // A renamed path still resolves — the segment is the key, the prefix is the tenant's business.
    const renamed: TenantContract = {
      ...doc,
      routes: [{ method: "POST", path: "/api/v2/agent/x/issue-comment", takesWriteBudgetUnit: true, since: "2.0.0" }],
    };
    expect(routeByName(renamed, "issue-comment")?.path).toBe("/api/v2/agent/x/issue-comment");
    expect(routeByName(doc, "nope")).toBeNull();
  });

  it("teamByKey / teamForTicket are case-insensitive on the key and typed on the miss", () => {
    const doc = loaded();
    const eng = teamByKey(doc, "eng");
    expect(eng.outcome).toBe("ok");
    if (eng.outcome !== "ok") return;
    expect(eng.team.id).toBe("team-eng");
    expect(teamForTicket(doc, "ENG-12")).toEqual(eng);
    expect(teamByKey(doc, "ZZZ")).toEqual({ outcome: "team-unknown", key: "ZZZ", known: doc.teams.map((t) => t.key ?? t.id) });
    expect(teamForTicket(doc, "no-dash-at-start")).toEqual({ outcome: "team-unknown", key: "NO", known: doc.teams.map((t) => t.key ?? t.id) });
    expect(teamForTicket(doc, "nodash")).toEqual({ outcome: "ticket-shape", ticket: "nodash" });
  });

  it("stageIdForSlot returns the mapped id, and names an unmapped or stale slot instead of guessing", () => {
    const doc = loaded();
    const eng = doc.teams[0]!;
    const research = eng.stages.research;
    expect(research).toBeDefined();
    expect(stageIdForSlot(eng, "research")).toEqual({ outcome: "ok", stateId: research!.stateId });
    // Deterministic, not "if the fixture happens to leave a slot unmapped": delete one and assert.
    const { research: _dropped, ...rest } = eng.stages;
    const partial = { ...eng, stages: rest };
    expect(stageIdForSlot(partial, "research")).toEqual({ outcome: "slot-unmapped", slot: "research", mapped: Object.keys(rest) });
    const stale = { ...eng, stages: { ...eng.stages, research: { ...research!, stateStillExists: false } } };
    expect(stageIdForSlot(stale, "research")).toEqual({ outcome: "slot-stale", slot: "research", stateId: research!.stateId });
  });

  it("labelIdFor resolves a contract label by name to its preferredId, reports absence, and passes an id through", () => {
    const doc = loaded();
    const eng = doc.teams[0]!;
    const ask = eng.labels.ask[0]!;
    expect(labelIdFor(eng, ask.name)).toEqual({ outcome: "ok", labelId: ask.preferredId });
    const absent = { ...eng, labels: { ...eng.labels, ask: [{ ...ask, scope: "absent" as const, preferredId: null, unscopedId: null, teamScopedId: null }] } };
    expect(labelIdFor(absent, ask.name)).toEqual({ outcome: "label-absent", name: ask.name, scope: "absent" });
    // Not a contract-listed name: treated as an id the caller already holds, exactly as the bundle does.
    expect(labelIdFor(eng, "label-some-other-id")).toEqual({ outcome: "ok", labelId: "label-some-other-id" });
  });
});
