// tenant-contract.ts — CTC-2004. The SHAPE of GET /api/v1/agent/contract as this SDK reads it, plus
// the pure accessors a consumer needs over it.
//
// ⛔ SELF-CONTAINED ON PURPOSE. The cloud declares this document in `@catalyst-cloud/types`
// (packages/types/src/tenant-contract.ts), a PRIVATE workspace package this SDK cannot import — the
// same constraint `src/types.ts` states for the change-feed contract. So this module is the SDK's own
// copy, structurally the cloud's, and test/tenant-contract.test.ts pins it against the fixture the
// cloud commits (packages/types/fixtures/tenant-contract.fixture.json — built by the real
// `buildTenantContract`, regenerated by `bun run contract:fixture`) so a cloud-side shape change
// reddens here as a fixture diff rather than surfacing as a silent wrong answer in a customer's skill.
//
// ⛔ NO FIELD BELOW CARRIES A DEFAULT. Every value is filled from the wire; a tenant fact the contract
// does not serve is reported as a typed miss (`slot-unmapped`, `label-absent`, `route-unknown`), never
// guessed. That is the whole point of the document (docs/agent-contract.md): a consumer that falls
// back to a remembered literal has reintroduced the defect the contract exists to retire.
//
// This module is free of any runtime-specific import — pure type declarations + plain functions — so
// it imports cleanly into a browser bundle or a node/bun app alike.

/** The eleven stage slots `teams[].stages` is keyed by. Served as `slots` on the wire, in this order. */
export type WorkflowSlot =
  | "dispatch"
  | "intake"
  | "research"
  | "plan"
  | "implement"
  | "remediate"
  | "verify"
  | "review"
  | "pr"
  | "done"
  | "canceled";

/** ⛔ `unscoped`, NOT `workspace` — the mirror's `labels.team_id` is advisory (NULL means either
 *  "genuinely workspace-scoped" or "not re-stamped yet"), so the document reports what was read. */
export type LabelScopeKind = "unscoped" | "team" | "absent";

export interface ContractLabel {
  name: string;
  unscopedId: string | null;
  teamScopedId: string | null;
  scope: LabelScopeKind;
  /** The id `scope` resolves to (the unscoped copy wins); `null` when `scope` is `absent`. */
  preferredId: string | null;
}

export interface ContractStage {
  /** Linear's state id — THE join key. Address stages by slot, and states by this. */
  stateId: string;
  /** The state's CURRENT name, read live — never the mapping's write-time snapshot. */
  name: string | null;
  type: string | null;
  /** False when the mapped id is not in the team's live stage set (archived, or re-minted). */
  stateStillExists: boolean;
  /** How the mapping was made: created | matched | chosen. */
  source: string;
}

export interface ContractReadinessCheck {
  id: string;
  state: "pass" | "fail" | "unknown";
  reason?: string;
  count?: number;
}

export interface ContractTeam {
  id: string;
  key: string | null;
  name: string | null;
  workflowMode: string;
  gitAutomation: string;
  /** Keyed by slot. An UNMAPPED slot is ABSENT — never a placeholder. */
  stages: Partial<Record<WorkflowSlot, ContractStage>>;
  labels: { ask: ContractLabel[]; hold: ContractLabel[]; release: ContractLabel[] };
  readiness: {
    /** `unchecked` means no verdict has ever been computed — a real answer, not `blocked`. */
    status: "ready" | "degraded" | "blocked" | "unchecked";
    checks: ContractReadinessCheck[];
    checkedAt: number | null;
    expiresAt: number | null;
    workflowRev: number | null;
  };
}

export interface ContractRoute {
  method: "GET" | "POST";
  path: string;
  /** Whether a call spends a unit of the per-host daily write budget. */
  takesWriteBudgetUnit: boolean;
  /** The contract version this route first appeared in. */
  since: string;
}

export interface ContractMergeRepository {
  repoId: string;
  owner: string;
  name: string;
  /** The EFFECTIVE policy after repo-wins-over-tenant precedence. */
  policy: string;
  policySource: "repo" | "tenant" | "default";
}

export interface ContractMergeCleanPassShape {
  kind: string;
  description: string;
  /** FALSE means the cloud does NOT accept this shape today. */
  honoured: boolean;
  ticket: string | null;
}

export interface ContractAdvanceRule {
  phase: string;
  result: "ok" | "failed";
  fromSlots: readonly WorkflowSlot[] | null;
  toSlot: WorkflowSlot | null;
  because: string;
}

export interface TenantContract {
  /** Semver over the DOCUMENT'S SHAPE (MAJOR: meaning changed/removed; MINOR: additive). */
  contractVersion: string;
  protocolVersion: number;
  /** The cloud states the freshness bounds; the CLIENT measures its own age against them. */
  cache: { maxAgeSeconds: number; staleRefusalSeconds: number };
  account: {
    id: string;
    slug: string;
    name: string;
    linearWorkspaceId: string | null;
    linearWorkspaceSlug: string | null;
  };
  apiPrefix: string;
  slots: readonly WorkflowSlot[];
  routes: readonly ContractRoute[];
  teams: ContractTeam[];
  vocabulary: {
    askLabelPrefix: string;
    askPhaseLabelPrefix: string;
    askMarkerLabel: string;
    releaseLabel: string;
    bookkeeping: {
      marker: string;
      prefixOnly: boolean;
      asciiCaseInsensitive: boolean;
      leadingWhitespaceTrimmed: boolean;
    };
  };
  askTemplate: {
    headings: { ask: string; options: string; defaultIfSilent: string; howToAnswer: string };
    howToAnswer: { withOptions: string; withoutOptions: string };
    optionBulletFormat: string;
    maxLetteredOptions: number;
    maxAskGenerations: number;
    example: string;
  };
  ladder: {
    phases: readonly string[];
    keying: string;
    keyingScope: string;
    /** `phases` is the full vocabulary; this says whether `intake` actually runs. */
    intakeEnabled: boolean;
    advance: readonly ContractAdvanceRule[];
  };
  thresholds: {
    scope: string;
    parkAfterConsecutiveFailures: number;
    remediateRoundCap: number;
    remediateEscalatedRoundBudget: number;
    remediateRewindBudget: number;
    retryBackoffMs: readonly number[];
    hostDailyWriteBudget: number;
  };
  merge: {
    policies: readonly string[];
    defaultPolicy: string;
    repositories: readonly ContractMergeRepository[];
    reviewerLogin: string;
    cleanPassShapes: readonly ContractMergeCleanPassShape[];
    cloudRemediateRequiredChecks: readonly string[];
    prLabels: { queueReady: string; handStepsHold: string; hold: string; preview: string };
  };
  readinessChecks: readonly { id: string; severity: string; needsAnswer: boolean }[];
  humans: readonly { linearUserId: string; role: "owner" | "admin" }[];
  asks: {
    /** `null` means NOT CONFIGURED, and a consumer must refuse rather than guess. */
    approvalsTeamId: string | null;
  };
}

/** The one path a consumer knows a priori — the address the document itself is served from. */
export const CONTRACT_ROUTE = "/api/v1/agent/contract";

/**
 * The document's top-level keys, as a runtime list, in lockstep with {@link TenantContract} — the
 * drift test asserts the two agree at compile time, and {@link readTenantContract} requires every
 * one of them on the wire. Kept alphabetical so the fixture comparison is order-independent.
 */
export const TENANT_CONTRACT_KEYS = [
  "account",
  "apiPrefix",
  "askTemplate",
  "asks",
  "cache",
  "contractVersion",
  "humans",
  "ladder",
  "merge",
  "protocolVersion",
  "readinessChecks",
  "routes",
  "slots",
  "teams",
  "thresholds",
  "vocabulary",
] as const satisfies readonly (keyof TenantContract)[];

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

/**
 * The shape guard the client applies to every 200 from the contract route. Structural, not
 * exhaustive: it requires every top-level key, and checks the load-bearing legs a consumer will
 * immediately index into (`cache`'s two bounds, `routes[]`'s method/path, `teams[]`'s id/stages/
 * labels/readiness, `slots[]`). A type predicate, so the narrowing is the compiler's — no cast.
 */
export function isTenantContract(value: unknown): value is TenantContract {
  if (!isRecord(value)) return false;
  for (const key of TENANT_CONTRACT_KEYS) if (!(key in value)) return false;
  if (typeof value["contractVersion"] !== "string") return false;
  if (typeof value["protocolVersion"] !== "number") return false;
  const cache = value["cache"];
  if (
    !isRecord(cache) ||
    typeof cache["maxAgeSeconds"] !== "number" ||
    typeof cache["staleRefusalSeconds"] !== "number"
  ) {
    return false;
  }
  const account = value["account"];
  if (!isRecord(account) || typeof account["id"] !== "string" || typeof account["slug"] !== "string") {
    return false;
  }
  const routes = value["routes"];
  if (
    !Array.isArray(routes) ||
    !routes.every(
      (r: unknown) =>
        isRecord(r) &&
        (r["method"] === "GET" || r["method"] === "POST") &&
        typeof r["path"] === "string" &&
        typeof r["takesWriteBudgetUnit"] === "boolean" &&
        typeof r["since"] === "string",
    )
  ) {
    return false;
  }
  const slots = value["slots"];
  if (!Array.isArray(slots) || !slots.every((s: unknown) => typeof s === "string")) return false;
  const teams = value["teams"];
  if (!Array.isArray(teams) || !teams.every(isContractTeam)) return false;
  const vocabulary = value["vocabulary"];
  if (
    !isRecord(vocabulary) ||
    !isRecord(vocabulary["bookkeeping"]) ||
    typeof vocabulary["bookkeeping"]["marker"] !== "string"
  ) {
    return false;
  }
  return isRecord(value["thresholds"]) && isRecord(value["merge"]) && isRecord(value["ladder"]);
}

function isNullableString(value: unknown): value is string | null {
  return value === null || typeof value === "string";
}

function isContractLabel(value: unknown): value is ContractLabel {
  return (
    isRecord(value) &&
    typeof value["name"] === "string" &&
    isNullableString(value["preferredId"]) &&
    (value["scope"] === "unscoped" || value["scope"] === "team" || value["scope"] === "absent")
  );
}

function isContractStage(value: unknown): value is ContractStage {
  return (
    isRecord(value) &&
    typeof value["stateId"] === "string" &&
    typeof value["stateStillExists"] === "boolean"
  );
}

/**
 * ⛔ THE NESTED LEGS ARE CHECKED, NOT JUST THEIR PRESENCE (Codex #65 r1, P2). The typed accessors
 * spread `team.labels.ask` and upper-case `team.key`; a document that passed the guard with
 * `labels: {}` or `key: 5` would reach them as `ok` and throw there, one call later, instead of
 * answering `shape` at the one place that read the wire.
 */
function isContractTeam(value: unknown): value is ContractTeam {
  if (!isRecord(value) || typeof value["id"] !== "string" || !isNullableString(value["key"])) {
    return false;
  }
  const stages = value["stages"];
  if (!isRecord(stages) || !Object.values(stages).every(isContractStage)) return false;
  const labels = value["labels"];
  if (
    !isRecord(labels) ||
    !(["ask", "hold", "release"] as const).every((k) => {
      const list = labels[k];
      return Array.isArray(list) && list.every(isContractLabel);
    })
  ) {
    return false;
  }
  const readiness = value["readiness"];
  return (
    isRecord(readiness) &&
    typeof readiness["status"] === "string" &&
    Array.isArray(readiness["checks"])
  );
}

/** {@link isTenantContract} as a read: the typed document, or `null` — never a throw, because the
 *  caller's answer to a malformed document is a typed `shape` outcome, not an exception. */
export function readTenantContract(value: unknown): TenantContract | null {
  return isTenantContract(value) ? value : null;
}

// ── Pure accessors — the bundle's contract.ts helpers, returning results instead of throwing ──────

/** The route whose LAST path segments are `name` — `"issue-comment"`, or a nested
 *  `"project-repositories/remove"`. The path prefix is never assumed. */
export function routeByName(doc: TenantContract, name: string): ContractRoute | null {
  const wanted = name.split("/").filter(Boolean);
  if (wanted.length === 0) return null;
  return (
    doc.routes.find((r) => {
      const segs = r.path.split("/").filter(Boolean);
      if (segs.length < wanted.length) return false;
      const from = segs.length - wanted.length;
      return wanted.every((w, i) => segs[from + i] === w);
    }) ?? null
  );
}

export type TeamLookup =
  | { outcome: "ok"; team: ContractTeam }
  | { outcome: "team-unknown"; key: string; known: string[] }
  | { outcome: "ticket-shape"; ticket: string };

export function teamByKey(doc: TenantContract, key: string): TeamLookup {
  const wanted = key.toUpperCase();
  const team = doc.teams.find((t) => (t.key ?? "").toUpperCase() === wanted);
  if (team === undefined) {
    return { outcome: "team-unknown", key: wanted, known: doc.teams.map((t) => t.key ?? t.id) };
  }
  return { outcome: "ok", team };
}

/** The team a ticket identifier belongs to, by its `KEY-` prefix. */
export function teamForTicket(doc: TenantContract, ticket: string): TeamLookup {
  const dash = ticket.indexOf("-");
  if (dash <= 0) return { outcome: "ticket-shape", ticket };
  return teamByKey(doc, ticket.slice(0, dash));
}

export type StageLookup =
  | { outcome: "ok"; stateId: string }
  | { outcome: "slot-unmapped"; slot: string; mapped: string[] }
  | { outcome: "slot-stale"; slot: string; stateId: string };

/** The Linear state id a slot maps to on this team. An unmapped slot and a stale mapping are two
 *  DIFFERENT answers (docs/agent-contract.md rule 1) and are reported by name. */
export function stageIdForSlot(team: ContractTeam, slot: string): StageLookup {
  const stage = team.stages[slot as WorkflowSlot];
  if (stage === undefined) return { outcome: "slot-unmapped", slot, mapped: Object.keys(team.stages) };
  if (!stage.stateStillExists) return { outcome: "slot-stale", slot, stateId: stage.stateId };
  return { outcome: "ok", stateId: stage.stateId };
}

export type LabelLookup =
  | { outcome: "ok"; labelId: string }
  | { outcome: "label-absent"; name: string; scope: LabelScopeKind };

/** Resolve a label by NAME through the contract's ask/hold/release lists to its `preferredId`. A name
 *  the contract does not list is passed through as an id the caller already holds (the contract
 *  only lists Catalyst's own labels); `scope: "absent"` is a real, reported answer, never an id. */
export function labelIdFor(team: ContractTeam, nameOrId: string): LabelLookup {
  const all = [...team.labels.ask, ...team.labels.hold, ...team.labels.release];
  const hit = all.find((l) => l.name === nameOrId);
  if (hit === undefined) return { outcome: "ok", labelId: nameOrId };
  if (hit.preferredId === null) return { outcome: "label-absent", name: hit.name, scope: hit.scope };
  return { outcome: "ok", labelId: hit.preferredId };
}
